-- SQL Script for CrimeShield Database Schema
-- Run this in the Supabase SQL Editor (https://supabase.com/dashboard)

-- Create events table to store logs, snapshots, and GPS telemetry
CREATE TABLE IF NOT EXISTS public.events (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    event_type text,
    status text,
    latitude double precision,
    longitude double precision,
    satellites integer,
    image_url text,
    reported_by text,
    notes text,
    CONSTRAINT events_pkey PRIMARY KEY (id)
);

-- Enable Realtime for live dashboard streaming
alter publication supabase_realtime add table public.events;
